"""initial migration

Revision ID: 14b040441721
Revises: f687741b9bfc
Create Date: 2025-06-01 22:48:24.473415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b040441721'
down_revision: Union[str, None] = 'f687741b9bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('games', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('games', 'last_played')
    op.drop_column('libraries', 'created_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('libraries', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('games', sa.Column('last_played', sa.DATETIME(), nullable=True))
    op.alter_column('games', 'platform',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('games', 'genre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
