"""Add User and Library models

Revision ID: f4faafdb9066
Revises: b75ec4dd4262
Create Date: 2025-05-31 21:05:57.721209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4faafdb9066'
down_revision: Union[str, None] = 'b75ec4dd4262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_library_association')
    op.add_column('libraries', sa.Column('game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'libraries', 'games', ['game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'libraries', type_='foreignkey')
    op.drop_column('libraries', 'game_id')
    op.create_table('game_library_association',
    sa.Column('game_id', sa.INTEGER(), nullable=True),
    sa.Column('library_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], )
    )
    # ### end Alembic commands ###
